#!/bin/sh

BASE_DIR=$(cd $(dirname $0); pwd)

git log --format="%H %P $(git rev-parse column_attr)" --grep='DBIx-Class/0.08/trunk@5634'
git log --format="%H %P $(git rev-parse warnfree)" --grep='DBIx-Class/0.08/trunk@4902'
git log --format="%H %P $(git rev-parse native_traits)" --grep='DBIx-Class/0.08/trunk@8226'
git log --format="%H %P $(git rev-parse resultsetcolumn_custom_columns)" --grep='DBIx-Class/0.08/trunk@5142'
git log --format="%H %P $(git rev-parse subquery)" --grep='DBIx-Class/0.08/branches/count_distinct@6147'
