#!/usr/bin/env perl
use strict;
use warnings;

use Cwd qw(realpath);
use File::Basename;
my $BASE_DIR = dirname realpath __FILE__;

my @merges = `git log --all --format='%H' --grep='(orig r'`;
chomp @merges;

for my $commit (@merges) {
    my $commit_data = `git cat-file commit $commit`;
    my @matched = $commit_data =~ /^[ ]r\d+\@[^\n]+\(orig[ ]r(\d+)\)/msxg;
    my ($parent_rev) = sort { $b <=> $a } @matched;
    unless ($parent_rev) {
        @matched = $commit_data =~ /^[ ][ ]r\d+\@[^\n]+\(orig[ ]r(\d+)\)/msxg;
        ($parent_rev) = sort { $b <=> $a } @matched;
        unless ($parent_rev) {
            @matched = $commit_data =~ /^[ ][ ][ ]r\d+\@[^\n]+\(orig[ ]r(\d+)\)/msxg;
            ($parent_rev) = sort { $b <=> $a } @matched;
            unless ($parent_rev) {
                warn "odd commit $commit.  merge but wrong format\n";
                next;
            }
        }
    }
    my $parent_commit = `git log --all --format='%H' -E --grep='git-svn-id: .*\@$parent_rev '`;
    chomp $parent_commit;
    my @parents = split /\n/, $parent_commit;
    if (@parents > 1) {
        my ($commit_branch) = $commit_data =~ /git-svn-id: ([^@]+)/;
        my $branch_parent_commit = `git log --all --format='%H' --grep='git-svn-id: $commit_branch\@$parent_rev '`;
        chomp $branch_parent_commit;
        if ($branch_parent_commit =~ /\n/) {
            $branch_parent_commit = `git log --all --format='%H' --grep='git-svn-id: .*/trunk\@$parent_rev '`;
            chomp $branch_parent_commit;
            if ($branch_parent_commit =~ /\n|^$/) {
                warn "odd commit $commit.  parent rev crosses branches\n";
                next;
            }
        }
        elsif (!$branch_parent_commit) {
            warn "odd commit $commit.  parent rev crosses branches\n";
            next;
        }
        $parent_commit = $branch_parent_commit;
    }
    unless ($parent_commit) {
        warn "can't find parent commit for $commit - r$parent_rev\n";
        next;
    }
    system "git show -s --format='%H %P $parent_commit' $commit";
}

