#!/usr/bin/env perl
use strict;
use warnings;

use Cwd qw(realpath);
use File::Basename;
my $BASE_DIR = dirname realpath __FILE__;

my @branches = `$BASE_DIR/unresolved-branches`;
chomp @branches;

BRANCH: for my $branch (@branches) {
    my $url = `git cat-file commit $branch | tail -1 | cut -d' ' -f2`;
    chomp $url;
    my ($path, $rev) = split /@/, $url;

    while (1) {
        $rev++;
        my $res = system "svn log -l1 $path\@$rev >/dev/null 2>/dev/null";
        if ($res) {
            printf "-%40s# deleted at %s\n", $branch, $rev;
            next BRANCH;
        }
    }
}

