#!/bin/sh

BASE_DIR=$(cd $(dirname $0); pwd)

rm -rf DBIx-Class
tar xzf $BASE_DIR/svn-imported.tar.gz
cd DBIx-Class

[[ $1 ]] && MAX_SCRIPT=$1 || MAX_SCRIPT=99
SCRIPTS=$( shopt -s nullglob; eval echo $BASE_DIR/{10..$MAX_SCRIPT}'.*')

for step in $SCRIPTS; do
    $step
done

